name: Manual Release

on: 
    workflow_dispatch:
        inputs:
            version:
                desecription: "Release version (e.g., 1.0.1)"
                required: true
                default: "1.0.1"
            environment:
                description: "Where to release"
                required: true
                default: "staging"
                type: choice
                options:
                    - staging
                    - production


jobs:
    release:
        runs-on: ubuntu-latest
        environment: ${{github.event.inputs.environment}}

        steps:
            - uses: actions/checkout@v4

            - name: Create release artifact
              run: |
                mkdir -p dist
                echo "Version: ${{github.event.inputs.version}}" > dist/release.txt
                echo "Commit: $GITHUB_SHA" >> dist/release.txt
                echo "Environment: ${{github.event.inputs.environment}}" >> dist/release.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: release-${{github.event.inputs.version}}-${{github.event.inputs.environment}}
                path: dist/